query getMainBanner($input: RootQueryToPostConnectionWhereArgs!, $first: Int!) {
  posts(where: $input, first: $first) {
    nodes {
      id
      excerpt
      title
      featuredImage {
        node {
          mediaItemUrl
        }
      }
    }
  }
}
