name: Lint

on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'
      - name: Run lint
        run: |
          yarn install --frozen-lockfile
          yarn verify
